name: platformio build

on:
  push:
    branches: ["main"]
    tags: ["v*"]
    paths-ignore: ["*.md"]
  pull_request:
    branches: ["main"]
    paths-ignore: ["*.md"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Setup Python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.9
          
      - name: Install platformio
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade platformio
          
      - name: Check
        run: |
          platformio check
          
      - name: Build
        run: |
          platformio run -e debug
